quixio/quix-samples

python/model/Hugging-Face-Model/.idea/.gitignore, python/model/Hugging-Face-Model/.idea/Threshold-Alert.iml, python/model/Hugging-Face-Model/.idea/inspectionProfiles/profiles_settings.xml, python/model/Hugging-Face-Model/.idea/modules.xml, python/model/Hugging-Face-Model/.idea/vcs.xml, python/model/Hugging-Face-Model/README.md, python/model/Hugging-Face-Model/build/dockerfile, python/model/Hugging-Face-Model/hugging_face_model.py, python/model/Hugging-Face-Model/main.py, python/model/Hugging-Face-Model/project.json, python/model/Hugging-Face-Model/repo.json, python/model/Hugging-Face-Model/requirements.txt
New hugging face item and small json file change
=> Hugging Face Item + small change in threshold json

python/model/Threshold-Alert/library.json, python/model/Threshold-Alert/threshold_function.py
=> Variable Names in Threshold item

python/model/Percentage-Alert/percentage_function.py
=> Percentage Verbosity

python/write/Real-Time-From-File/main.py
Little cleaning in this library item (same functionality)
=> Small cleaning in real time file

python/write/Fraud-Ingest/library.json
DefaultFile pointing to main.py
=> Reviews pre launch 7

csharp/empty/library.json, csharp/model/downsample_example/library.json, csharp/read/complete example/library.json, csharp/read/hello world/library.json, javascript/read/library.json, nodejs/empty/library.json, python/empty/library.json, python/model/Data-Filtering/README.md, python/model/Data-Filtering/library.json, python/model/NY-Bikes-Predictions/library.json, python/read/Complete-Example/library.json, python/read/Hello-Panda/library.json, python/read/Hello-World/library.json, python/write/Hello-Pandas/library.json, python/write/Hello-World/library.json, python/write/NY-Citibikes/library.json, python/write/Open-Weather/library.json
Remove some input default values and refactored others
=> Remove some input default values and refactored others

python/destinations/slack-notifications/main.py, python/destinations/slack-notifications/quix_function.py, python/transformations/Quix-Lambda/main.py, python/transformations/Quix-Lambda/quix_function.py
* Slack improvements
* Quix function fix
=> Slack improvements (#100)

csharp/destinations/ably-sink/.gitignore, csharp/destinations/ably-sink/AblySink.sln, csharp/destinations/ably-sink/AblySink/AblySink.csproj, csharp/destinations/ably-sink/AblySink/Program.cs, csharp/destinations/ably-sink/README.md, csharp/destinations/ably-sink/build/dockerfile, csharp/destinations/ably-sink/library.json, csharp/destinations/ably-sink/nuget.config, csharp/destinations/ably-sink/repo.json, csharp/sources/ably-hub/.gitignore, csharp/sources/ably-hub/AblyHubSource.sln, csharp/sources/ably-hub/AblyHubSource/AblyHubSource.csproj, csharp/sources/ably-hub/AblyHubSource/Program.cs, csharp/sources/ably-hub/README.md, csharp/sources/ably-hub/build/dockerfile, csharp/sources/ably-hub/library.json, csharp/sources/ably-hub/nuget.config, csharp/sources/ably-hub/repo.json
=> Ably Hub source

python/sources/Car-Data-Realtime/README.md, python/sources/Car-Data-Realtime/library.json, python/sources/Real-Time-From-File/main.py
Minor details on docs and variable namings
=> Final improvements on real time

python/transformations/Realtime-Dashboard/helpers.py, python/transformations/Realtime-Dashboard/in_memory_view.py, python/transformations/Realtime-Dashboard/main.py
=> Bug/realtime dashboard fixes (#186)

python/sources/Twitter-Stream/main.py
merge fix from main provided by community member - Rutger
=> Fix the Twitter stream source (#185)

csharp/sources/external-topic-retransmitter/Program.cs, csharp/sources/external-topic-retransmitter/Retransmitter.csproj, csharp/sources/external-topic-retransmitter/library.json
- Turn topic retransmitter to a connector with feedback
- Fix rare edgecase by upgrading SDK version
=> Convert Topic retransmitter to a fully fledged connector with feedback

csharp/sources/external-topic-retransmitter/Program.cs, csharp/sources/external-topic-retransmitter/Retransmitter.csproj, csharp/sources/external-topic-retransmitter/library.json
- Turn topic retransmitter to a connector with feedback
- Fix rare edgecase by upgrading SDK version
=> - Turn topic retransmitter to a connector with feedback (#206)

csharp/sources/azure-iot-hub/azureiot/Program.cs, csharp/sources/external-topic-retransmitter/Program.cs, csharp/sources/external-topic-retransmitter/Retransmitter.csproj
- Fix Azure IoT hub
- Fix missing consumer group for topic replicator
=> Smaller fixes

csharp/sources/azure-iot-hub/azureiot/Program.cs, csharp/sources/external-topic-retransmitter/Program.cs, csharp/sources/external-topic-retransmitter/Retransmitter.csproj
* Fix Azure IoT hub
* Fix missing consumer group for topic replicator
* Update to latest version of SDK to combat consumer issue in Retransmitter
=> Smaller fixes (#208)

csharp/sources/azure-iot-hub/azureiot/Program.cs
Properties are attached to the message payload.
=> Azure IoT hub improvements

csharp/destinations/snowflake/Quix.Snowflake.Infrastructure/TimeSeries/Models/SnowflakeConnectionConfiguration.cs, csharp/destinations/snowflake/Quix.Snowflake.Infrastructure/TimeSeries/Repositories/TimeSeriesWriteRepository.cs
Handle multi topics
Fix bug when batching inserts
=> Snowflake to handle multiple topics

python/destinations/Prometheus-sink/library.json
Co-authored-by: Steve R <steve@quix.ai>
=> Fix Prometheus config (#221)

csharp/destinations/snowflake/Quix.Snowflake.Infrastructure/Shared/SnowflakeQuery.cs, csharp/destinations/snowflake/Quix.Snowflake.Infrastructure/TimeSeries/Repositories/TimeSeriesWriteRepository.cs
This is to avoid topics that start with a number breaking Snowflake
=> Prefix the tables

python/destinations/streamlit/requirements.txt
=> Peg streamlit to 1.11.1

csharp/destinations/SQLServer/library.json, csharp/destinations/ably-sink/library.json, csharp/destinations/redshift-sink/library.json, csharp/destinations/snowflake/library.json, csharp/sources/ably-hub/library.json, csharp/sources/awair-connector/library.json, csharp/sources/car-data/library.json, csharp/sources/demo-data/library.json, python/destinations/MQTT/library.json, python/destinations/Prometheus-sink/library.json, python/destinations/S3/library.json, python/destinations/Twilio/library.json, python/destinations/slack-notifications/library.json, python/sources/AmazonKinesis/library.json, python/sources/Car-Data-Realtime/library.json, python/sources/Car-Data/library.json, python/sources/Coin-API/library.json, python/sources/Confluent-Kafka/library.json, python/sources/Currency-Exchange-Rates/library.json, python/sources/Electric-Motor-Data/library.json, python/sources/GooglePubSub/library.json, python/sources/MQTT/library.json, python/sources/RSS/library.json, python/sources/Reddit/library.json, python/sources/Snowplow/library.json
=> Fix some library item names

nodejs/advanced/Image-Processing-UI/src/app/app.component.ts, nodejs/advanced/Image-Processing-UI/src/app/services/environment-variables.service.ts, nodejs/advanced/QR Settings Share/ui/source/app/services/quix.service.ts, python/sources/TFL-Camera-Feed/library.json
QR Settings Share
TFL UI
TFL Cameras
=> Fixes for library items

nodejs/advanced/Image-Processing-UI/src/app/app.component.ts, nodejs/advanced/Image-Processing-UI/src/app/services/environment-variables.service.ts, nodejs/advanced/QR Settings Share/ui/source/app/services/quix.service.ts, python/sources/TFL-Camera-Feed/library.json
* Fix TFL UI Website
* Fixes for QR Setting Sharer
* Hide TFL API Key
=> Fixes for library items (#279)

python/transformations/NY-Bikes-Predictions/requirements.txt
=> NY Bikes Prediction transformation

nodejs/web-api/library.json, nodejs/web-api/src/app.ts
- Add link to JSON file in Swagger UI
- Add environmental variable to modify port for testing purposes
=> Improvements to NodeJs web API template

csharp/advanced/QuixTracker/library.json, python/sources/Fraud-Data-Source/library.json, python/sources/NY-Citibikes/library.json, python/sources/Open-Weather/library.json, python/sources/TFL-Bikepoint/library.json, python/transformations/NY-Bikes-Predictions/library.json
Remove Mobility from Popular Subjects
Remove Quick Start from Use Case
=> Library items categories change

nodejs/advanced/QR Settings Share/ui/src/app/components/lobby/lobby.component.ts
=> Add rider and device id to QR code

python/transformations/empty-template-new/README.md, python/transformations/empty-template-new/build/dockerfile, python/transformations/empty-template-new/library.json, python/transformations/empty-template-new/main.py, python/transformations/empty-template-new/requirements.txt
Template for transformations. 
Uses new open source library (QuixStreams)
=> Task/quix streams transformation (#333)

applications/image-processing/webcam-input/src/app/app.component.ts
Might be blank if user has not accepted use of cam yet
=> Retry getting webcam list till there is something to use

.gitignore, csharp/destinations/empty-template/ReadHelloWorld/Program.cs, csharp/destinations/empty-template/ReadHelloWorld/ReadHelloWorld.csproj, csharp/destinations/empty-template/build/dockerfile, csharp/sources/empty-template/WriteHelloWorld/Program.cs, csharp/sources/empty-template/WriteHelloWorld/WriteHelloWorld.csproj, csharp/sources/empty-template/build/dockerfile, csharp/transformations/empty-template/HelloWorldModel.sln, csharp/transformations/empty-template/HelloWorldModel/HelloWorldModel.csproj, csharp/transformations/empty-template/HelloWorldModel/Program.cs, csharp/transformations/empty-template/README.md, csharp/transformations/empty-template/build/dockerfile, csharp/transformations/empty-template/library.json, csharp/transformations/empty-template/nuget.config
- Use `QuixStreams 0.5.0`
- Use `net7.0`
=> Update C# templates

applications/image-processing/webcam-input/src/app/app.component.ts, applications/image-processing/webcam-input/src/app/services/quix.service.ts, nodejs/advanced/Image-Processing-UI/src/app/app.component.ts, nodejs/advanced/Image-Processing-UI/src/app/services/quix.service.ts, python/transformations/Image-processing-object-detection/image_processing.py, python/transformations/Image-processing-object-detection/main.py, python/transformations/Image-processing-object-detection/quix_function.py, python/transformations/Image-processing-object-detection/requirements.txt
Uses QuixStreams
Fixed some bugs
=> Update image processing code

nodejs/advanced/QR Settings Share/api/main.js
Log something to let the portal / platform know it's alive
=> Fix QR Settings Share

csharp/sources/demo-data/library.json, python/destinations/BigQuery/main.py, python/destinations/BigQuery/quix_function.py, python/postman/library.json, python/sources/SQL-CDC/build/dockerfile, python/sources/simple-csv/library.json, python/transformations/TFL-Camera-Frame-Extraction/requirements.txt
=> Release Samples 2023-08-001

python/destinations/S3/README.md, python/destinations/S3/library.json, python/destinations/S3/main.py
=> Update S3 Sink (#433)

python/transformations/empty-template-sdf/README.md, python/transformations/empty-template-sdf/build/dockerfile, python/transformations/empty-template-sdf/library.json, python/transformations/empty-template-sdf/main.py, python/transformations/empty-template-sdf/requirements.txt
=> SDF transformation (#444)

python/destinations/influxdb_3/README.md, python/destinations/influxdb_3/library.json, python/destinations/influxdb_3/main.py, python/destinations/influxdb_3/requirements.txt, python/sources/influxdb_3/main.py, python/sources/influxdb_3/requirements.txt
=> Updates to InfluxDB 3 connectors

README.md
This is a replacement of https://github.com/quixio/quix-samples/pull/534
=> Update README.md to add Quix CLI bits instead of direct sign-up to Quix Cloud

python/destinations/MQTT/dockerfile, python/destinations/big_query/dockerfile, python/destinations/confluent_kafka/dockerfile, python/destinations/hivemq/dockerfile, python/destinations/influxdb_3/dockerfile, python/destinations/postgres/dockerfile, python/destinations/redis_dest/dockerfile, python/destinations/slack_notifications/dockerfile, python/destinations/starter_destination/dockerfile, python/destinations/websocket/dockerfile, python/sources/MQTT/dockerfile, python/sources/confluent_kafka/dockerfile, python/sources/demo_data/dockerfile, python/sources/hivemq/dockerfile, python/sources/influxdb_2/dockerfile, python/sources/influxdb_3/dockerfile, python/sources/postgres_cdc/dockerfile, python/sources/redis_source/dockerfile, python/sources/segment_webhook/dockerfile, python/sources/simple_csv/dockerfile, python/sources/snowplow_source/dockerfile, python/sources/starter_source/dockerfile, python/sources/web_api_gateway/dockerfile, python/transformations/event_detection/dockerfile, python/transformations/hugging_face_model/dockerfile, python/transformations/starter_transformation/dockerfile
This new dockerfile makes sharing folders possible
=> Update default dockerfile

.gitignore, python/destinations/websocket/README.md, python/destinations/websocket/library.json, python/destinations/websocket/main.py, python/destinations/websocket/requirements.txt
Updated Websocket destination to work with newer version of Quix Streams and websockets.
Cleaned up a few things in it.
Also cleaned up .gitignore (didn't remove anything, just organized and added a couple entries).
=> Websocket destination reqs update

python/sources/confluent_kafka/README.md, python/sources/confluent_kafka/library.json, python/sources/confluent_kafka/main.py
There was a bug in kafka source library that makes the the input read from quix broker rather than external kafka. 
Added support for certificate as well
=> Fix bug in kafka source and add certificate support

docker/redis_server/dockerfile, docker/redis_server/init.sh, docker/redis_server/redis.conf
Adjusted docker build to ensure state works as expected.
=> fix redis state

python/sources/opc_ua_client/library.json, python/sources/opc_ua_client/main.py, python/sources/opc_ua_client/opc_ua_source.py
Force the app to shutdown when exceptions occur during a change notification (with the option to ignore such errors, if desired). Also correctly shuts down when the server connection is lost.
Also adjusted some logging and cleaned up some things.
Please check out my comments for other outstanding questions.
(Tested against a locally running server)
=> fix OPC_UA to properly shut down upon errors

python/destinations/TDengine/README.md, python/destinations/TDengine/library.json, python/destinations/TDengine/main.py, python/destinations/TDengine/requirements.txt
corresponds with PR https://github.com/quixio/quix-streams/pull/979
=> Destination: TDEngine - add changes for newest sink additions
